[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "microphone=(self)"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
